# Generated by Django 3.0.4 on 2020-03-18 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_auto_20200318_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abt',
            name='aboutme',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='abt',
            name='moreaboutme',
            field=models.TextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='intro',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='intro',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='text',
            field=models.TextField(max_length=500),
        ),
    ]
