# Generated by Django 3.0.4 on 2020-03-19 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_auto_20200318_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intro',
            old_name='profile',
            new_name='profile1',
        ),
    ]
